# Generated by Django 4.1.6 on 2023-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_bank_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='valueReceivable',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cost',
            name='valuePayable',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
