# Generated by Django 4.1.6 on 2023-02-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cash_valuereceivable_alter_cost_valuepayable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='valueReceivable',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cost',
            name='valuePayable',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
